fjsp/CpModel.py, fjsp/Model.py, fjsp/ProblemData.py, fjsp/plot.py
Closes #10. This PR adds three precedence constraints: previous, before, and same unit. This allows to force one operation to be scheduled after another on the same machine.
=> Ordering and same unit precedence constraints

fjsp/Model.py, fjsp/ProblemData.py, fjsp/Solution.py, fjsp/cp/constraints.py, fjsp/cp/objectives.py, fjsp/cp/variables.py, fjsp/plot.py
This is a follow-up PR on #33 to simplify the code. It gets rid of the indices on Job, Machine and Operations, which I initially used since I did not have a convention yet for indexing.
It also separates the processing times from the `Operation` object.
=> Remove object indices

fjsp/ProblemData.py, fjsp/cp/constraints.py, fjsp/cp/default_model.py, fjsp/cp/objectives.py, fjsp/cp/variables.py, fjsp/plot.py
Closes #44.
Also renames the variables into `<abbreviation>_vars`. This is more explicit, since we are distinguishing between three types of "operations" or "jobs":
- `Operation` class (data)
- `operation` index (in the `ProblemData.idx` list)
- `operation` variable
=> Introduce job interval variable

fjsp/Model.py, fjsp/ProblemData.py, fjsp/cp/variables.py, tests/examples/test_Model.py, tests/examples/test_ProblemData.py, tests/examples/test_flowshop.py, tests/examples/test_jobshop.py, tests/test_Model.py, tests/test_ProblemData.py
Closes #52.
In summary:
- `ProblemData.processing_times` now expects a dictionary with `(machine, operation)` and duration key-value pairs. The matrix was unnecessary because the data is very sparse and we don't need any matrix computations anyway. (Note: this may change when we use heuristics!)
- `ProblemData.machine2ops` is removed and should be inferred from the keys in `ProblemData.processing_times` instead.
=> Store processing times in dict

pyjobshop/Model.py, pyjobshop/ProblemData.py, pyjobshop/cp/constraints.py, pyjobshop/cp/default_model.py, tests/examples/test_ProblemData.py, tests/test_Model.py, tests/test_ProblemData.py
This PR:
- Is part of #43.
- Adds the weight and due date attribute to `Job`.
- Redefines behavior of the current `job.deadline` attribute, which was interpreted as due date.
=> Job weight and due date

pyjobshop/Model.py, pyjobshop/ProblemData.py, pyjobshop/cp/constraints.py, pyjobshop/cp/default_model.py, tests/test_Model.py, tests/test_ProblemData.py
This PR adds the `allow_overlap` attribute on machines. Setting this parameter to true allows operations to overlap on machines, which will be eventually useful for batching and storage resources.
=> Allow overlap on machines

.github/workflows/CI.yml, pyproject.toml
This PR makes the `cplex` package dependency optional.  
After #26, OR-Tools will become the default. But I'm having some CPLEX dependency issues already (see #49) which makes development a bit difficult. This PR (hopefully) fixes that.
=> Make CPLEX optional

docs/source/index.rst, pyjobshop/Model.py, pyjobshop/ProblemData.py, pyjobshop/Result.py, pyjobshop/Solution.py, pyjobshop/cp/default_model.py, pyjobshop/plot.py
This PR removes type hints from parameter descriptions in docstrings. The reason is that the documentation infers the types from the signature; adding these again in the docstrings results in faulty renders. Part of #63.
=> Remove type hints in docstrings

docs/source/api/pyjobshop.rst, docs/source/conf.py, examples/simple_example.ipynb, pyjobshop/Model.py, pyjobshop/ProblemData.py, pyjobshop/__init__.py, pyjobshop/cp/__init__.py, pyjobshop/cp/constraints.py, pyjobshop/cp/default_model.py, pyproject.toml, tests/test_Model.py, tests/test_ProblemData.py
This PR merges TimingPrecedence and AssignmentPrecedence into one `Constraint` class. This significantly simplifies the interface. 
I want to distinguish between the constraint types at some point to support delays in timing precedence, but for now this is OK.
Part of #78.
=> Merge TimingPrecedence and AssignmentPrecedence to Constraint

pyjobshop/Model.py, pyjobshop/ProblemData.py, pyjobshop/cp/constraints.py, pyjobshop/cp/default_model.py, pyjobshop/cp/variables.py, tests/test_Model.py, tests/test_ProblemData.py
This PR removes the Operation class's optional field and process plans. This is an attempt to simplify the feature set to make OR-Tools support more convenient.
=> Remove Operation optionality and process plans

pyjobshop/Model.py, pyjobshop/ProblemData.py, pyjobshop/cp/constraints.py, pyjobshop/cp/default_model.py, tests/test_Model.py, tests/test_ProblemData.py
This PR removes machine downtimes. Like #111, this is an attempt to make the codebase simpler to integrate OR-tools more easily.
Related: 
- #96 
- #28
=> Remove Machine downtimes

pyjobshop/ortools/constraints.py, pyjobshop/ortools/default_model.py, pyjobshop/ortools/variables.py, tests/test_ProblemData.py
This PR introduces the Previous constraint for OR-Tools (part of #26). Specifically:
- Introduces the `SequenceVar` class to model CP Optimizer-like sequence variables
- Implements the Previous constraint 
For future reference, it's good to note that our choice for activating circuit constraints separately is for performance reasons. I have not checked whether this matters (as presolve could possibly deal with this).
=> [OR-Tools] Previous constraint

pyjobshop/Model.py, pyjobshop/ProblemData.py, pyjobshop/ortools/constraints.py, pyjobshop/ortools/create_model.py, pyjobshop/ortools/variables.py, tests/test_ProblemData.py
This PR refactors the implementation of CP models. In particular:
- Constraints that directly apply to the corresponding variable (e.g., release date for job) are moved to the variable instantiation functions. 
- Constraints are renamed to reflect the result better.
- Turn `job.deadline` into a numerical value with a sensible default, as well as `operation.start` and `operation.end` times.
=> [OR-Tools] Refactor and better defaults

README.md, pyjobshop/ProblemData.py, pyjobshop/cpoptimizer/constraints.py, pyjobshop/cpoptimizer/create_model.py, pyjobshop/cpoptimizer/objectives.py, pyjobshop/cpoptimizer/variables.py, pyjobshop/ortools/constraints.py, pyjobshop/ortools/objectives.py, pyjobshop/ortools/variables.py, pyjobshop/utils.py, tests/test_ProblemData.py, tests/test_utils.py
This PR refactors the CP Optimizer implementation following the same adjustments as made in #130. Some differences:
- Instead of initializing variables with the bounds on start/end/duration, we use setters. I find this easier to read and maintain.
=> [CP Optimizer] Refactor implementation

pyjobshop/Model.py, pyjobshop/ProblemData.py, pyjobshop/cpoptimizer/variables.py, pyjobshop/ortools/objectives.py, pyjobshop/ortools/variables.py, pyjobshop/utils.py, tests/test_Model.py, tests/test_ProblemData.py, tests/test_utils.py
This PR renames `planning_horizon` to the less verbose `horizon`
=> Rename planning horizon

pyjobshop/ortools/constraints.py, pyjobshop/ortools/variables.py
Part of #123. I came across this issue when implementing #136, where large FJSP instances take forever to create.
=> [OR-Tools] Lazy generate arc sequence variables

.github/workflows/CI.yml, pyproject.toml
This PR:
- Allows higher versions of Python.
- Historical note: CPLEX 21.1.0 came only with Python 3.9 and Python 3.10, so I restricted the Python versions at the time.
- Bumps CPLEX to 21.1.1.2, which supports Python 3.11.
=> Allow newer Python versions and bump CPLEX

pyjobshop/__init__.py, pyjobshop/cli.py, pyjobshop/read.py, pyproject.toml
This PR separates instance reading from CLI (so users can use `read.py` to read FJSPLIB) and allows parallel solving of instances. This is helpful when using the cluster to solve multiple instances in parallel.
=> Separate instance reading and allow parallel solving instances

pyjobshop/Model.py, pyjobshop/ProblemData.py, pyjobshop/cpoptimizer/ConstraintsManager.py, pyjobshop/cpoptimizer/Solver.py, pyjobshop/cpoptimizer/VariablesManager.py, pyjobshop/ortools/ConstraintsManager.py, pyjobshop/ortools/Solver.py, pyjobshop/ortools/VariablesManager.py, pyjobshop/utils.py, tests/test_Model.py, tests/test_ProblemData.py, tests/test_utils.py
This PR replaces processing times and task alternatives for the more general concept of processing modes. It currently only works for one machine per mode and no demands.
Part of #68.
=> Replace processing times and task alternatives for modes

pyjobshop/cpoptimizer/ConstraintsManager.py, pyjobshop/cpoptimizer/ObjectiveManager.py, pyjobshop/cpoptimizer/VariablesManager.py
The CpoModel methods are not correctly typed, so IDEs are unable to show docstrings for those methods. This PR replaces the methods with the functions that are correctly type hinted.
=> [CP Optimizer] Use functions instead of CpoModel methods

.github/workflows/CI.yml, docs/source/setup/installation.rst, pyproject.toml
Maintenance chore. New `cplex` is now compatible with Python 3.12.
=> Upgrade CPLEX to be Python 3.12 compatible

pyjobshop/Model.py, pyjobshop/ProblemData.py, pyjobshop/solvers/cpoptimizer/Variables.py, pyjobshop/solvers/ortools/Objective.py, pyjobshop/solvers/ortools/Variables.py, tests/test_Model.py, tests/test_ProblemData.py
This PR removes the horizon argument to ProblemData. I have never really used this and the benchmarks don't improve by setting this value (to some simple upper bound). So it's just better to remove it altogether. If users still want to set a horizon value, they can do so by setting `Task.latest_end`.
<details>
**Notes**:
In particular:
- New code additions must be well formatted. Changes should pass the pre-commit …
=> Remove horizon

examples/flexible_job_shop.ipynb
If I'm not mistaken, association of a task with a job is already done upon the task's creation.  This can be removed from the list of "more things that we need to add to the model".
Minor: the last entry doesn't require a semicolon; add "and" before the last item.
<details>
**Notes**:
In particular:
- New code additions must be well formatted. Changes should pass the pre-commit workflow, which you can set up locally …
=> Small FJSP notebook update: amend description of task creation

examples/objectives_examples.ipynb, pyjobshop/Model.py, pyjobshop/ProblemData.py, pyjobshop/solvers/ortools/Objective.py, tests/test_Model.py, tests/test_ProblemData.py
This PR:
I've added an OR-Tools implementation, tests, and documentation for the total setup time objective.
Please note that the CP optimizer implementation hasn't been done yet, so test_total_setup_time function will fail.
If there are any mistakes or parts that don't align with your design philosophy, please feel free to point them out or provide corrections!
=> [CP-SAT] Total setup time objective

README.md, docs/source/index.rst, examples/objectives_examples.ipynb, pyjobshop/Model.py, pyjobshop/ProblemData.py, pyjobshop/solvers/cpoptimizer/Objective.py, pyjobshop/solvers/ortools/Objective.py, tests/test_Model.py, tests/test_ProblemData.py
This PR removes the maximum lateness. Unlike all other objectives, maximum lateness can take on negative values. This has some annoying interactions with #269 for example. I think it's easiest to only consider objectives that can be strictly non-negative.
<details>
**Notes**:
In particular:
- New code additions must be well formatted. Changes should pass the pre-commit workflow, which you can set up locally using …
=> Remove maximum lateness
