Model.py
cp.py
examples/flowshop.py

This PR adds operations precedence types to the operations graph.

Operation precendence types

---

fjsp/CpModel.py

This PR modularizes the construction of the CP model. This is useful for extensions or different problem models that need different constraints like #18.

Modularize CpModel

---

fjsp/Model.py
fjsp/ProblemData.py
fjsp/cp/constraints.py
jobshop.py

Setup times

---

fjsp/Model.py
fjsp/ProblemData.py
fjsp/cp/constraints.py
flowshop.py
jobshop.py
pyproject.toml
tests/test_ProblemData.py

Related to #11. I think networkx is a bit of an overkill for what I'm doing right now.

Replace graphs in favor of precedence and accessibility data

---

fjsp/Model.py
fjsp/ProblemData.py
fjsp/cp/constraints.py
fjsp/cp/default_model.py
tests/examples/test_ProblemData.py
tests/test_ProblemData.py

Earliest/latest Operation parameters

---

tests/test_Model.py

Model tests

---

pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/cp/constraints.py
pyjobshop/cp/default_model.py
pyjobshop/cp/variables.py
tests/examples/test_ProblemData.py
tests/test_Model.py
tests/test_ProblemData.py

Optional operations

---

.github/workflows/CI.yml
.readthedocs.yaml
docs/Makefile
docs/make.bat
docs/source/api/pyjobshop.rst
docs/source/conf.py
docs/source/index.rst
pyjobshop/Model.py
pyproject.toml

Part of #63.
- A simple documentation built with Sphinx.
- Readthedocs for hosting.

Setup documentation

---

pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/cp/constraints.py
pyjobshop/cp/default_model.py
tests/examples/test_ProblemData.py
tests/test_Model.py
tests/test_ProblemData.py

Machine availability

---

pyjobshop/plot.py

Larger color map and custom axes

---

pyjobshop/ProblemData.py
pyjobshop/cp/default_model.py
pyjobshop/cp/objectives.py
tests/test_Model.py
tests/test_ProblemData.py

Tardy jobs objective

---

pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/cp/constraints.py
pyjobshop/cp/default_model.py
tests/test_Model.py
tests/test_ProblemData.py

Planning horizon

---

pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/cp/constraints.py
tests/test_Model.py
tests/test_ProblemData.py

Machine downtimes

---

pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/cp/constraints.py
pyjobshop/cp/default_model.py
pyjobshop/cp/variables.py
tests/test_Model.py
tests/test_ProblemData.py

Fixed operation duration

---

examples/simple_example.ipynb
pyjobshop/Model.py
pyjobshop/Result.py
pyjobshop/Solution.py
pyjobshop/__init__.py
pyjobshop/constants.py
pyjobshop/cpoptimizer/__init__.py
pyjobshop/cpoptimizer/solve.py
pyjobshop/ortools/__init__.py
pyjobshop/ortools/constraints.py
pyjobshop/ortools/default_model.py
pyjobshop/ortools/objectives.py
pyjobshop/ortools/solve.py
pyjobshop/ortools/variables.py
pyjobshop/solve.py
pyproject.toml
tests/test_Model.py
tests/test_ProblemData.py
tests/test_Result.py

This PR introduces a general `solve` interface that is used to streamline the multiple-solver interfaces. Closes #114.

Solve interface

---

pyjobshop/Model.py
pyjobshop/cpoptimizer/solve.py
pyjobshop/ortools/solve.py
pyjobshop/solve.py

Number of workers argument

---

pyjobshop/ortools/constraints.py
pyjobshop/ortools/objectives.py
pyjobshop/ortools/variables.py
pyproject.toml

[OR-Tools] Upgrade to OR-Tools 9.10+

---

pyjobshop/ortools/constraints.py
pyjobshop/ortools/default_model.py
pyjobshop/ortools/objectives.py

This PR implements the total completion time, total tardiness, and number of tardy jobs objective functions for Google OR-Tools. Part of #26.

[OR-Tools] Completion times and tardiness

---

pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/cpoptimizer/constraints.py
pyjobshop/ortools/constraints.py
pyjobshop/plot.py
tests/test_Model.py
tests/test_ProblemData.py
tests/test_utils.py

Remove `job2tasks`

---

pyjobshop/constants.py

Increase ``MAX_VALUE`` to ``2**51``

---

pyjobshop/ProblemData.py
pyjobshop/utils.py
tests/test_Model.py
tests/test_ProblemData.py
tests/test_utils.py

Raise when tasks have no processing times

---

examples/flexible_job_shop.ipynb
examples/hybrid_flow_shop.ipynb
pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/cpoptimizer/constraints.py
pyjobshop/ortools/constraints.py
pyproject.toml
tests/test_Model.py
tests/test_ProblemData.py

Refactor Model interface for constraints

---

pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/cpoptimizer/constraints.py
pyjobshop/ortools/constraints.py
tests/test_Model.py
tests/test_ProblemData.py

Before constraint

---

pyjobshop/cpoptimizer/solve.py
pyjobshop/ortools/solve.py
pyjobshop/solve.py
pyproject.toml
tests/test_solve.py

Pass additional solver parameters to solve

---

pyjobshop/Model.py
pyjobshop/ProblemData.py
tests/test_ProblemData.py

`ProblemData.replace`

---

pyjobshop/cpoptimizer/constraints.py
pyjobshop/cpoptimizer/create_model.py
pyjobshop/cpoptimizer/variables.py
pyjobshop/ortools/constraints.py
pyjobshop/ortools/create_model.py
pyjobshop/ortools/solve.py
pyjobshop/ortools/variables.py

Rename `AssignmentVar` to `TaskAltVar`

---

cpo_config.py
pyjobshop/cpoptimizer/create_model.py
pyjobshop/cpoptimizer/solve.py
pyjobshop/cpoptimizer/variables.py
pyjobshop/ortools/create_model.py
pyjobshop/ortools/objectives.py
pyjobshop/ortools/solve.py
pyjobshop/ortools/variables.py
pyjobshop/solve.py
pyproject.toml
tests/test_solve.py

Pass initial solution to solve

---

pyjobshop/Result.py
pyjobshop/ortools/Solver.py
tests/ortools/test_Solver.py

[OR-Tools] Clear hints

---

docs/source/api/pyjobshop.rst
pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/cpoptimizer/create_model.py
pyjobshop/cpoptimizer/objectives.py
pyjobshop/ortools/ObjectiveManager.py
pyjobshop/ortools/Solver.py
tests/test_Model.py
tests/test_ProblemData.py

Weighted objective

---

pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/cpoptimizer/ObjectiveManager.py
pyjobshop/ortools/ObjectiveManager.py
tests/test_Model.py
tests/test_ProblemData.py

Total earliness objective

---

README.md
docs/source/index.rst
pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/cpoptimizer/ObjectiveManager.py
pyjobshop/ortools/ObjectiveManager.py
tests/test_Model.py
tests/test_ProblemData.py

Part of #195. In practice, completion times are subsetted by flow time so there is no reason to have them separately.

Rename completion time to flow time

---

README.md
conftest.py
docs/source/api/pyjobshop.rst
docs/source/index.rst
docs/source/setup/intro_to_scheduling.rst
examples/flexible_job_shop.ipynb
examples/hybrid_flow_shop.ipynb
examples/project_scheduling.ipynb
examples/quick_examples.ipynb
examples/simple_example.ipynb
pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/Solution.py
pyjobshop/__init__.py
pyjobshop/cpoptimizer/ConstraintsManager.py
pyjobshop/cpoptimizer/Solver.py
pyjobshop/cpoptimizer/VariablesManager.py
pyjobshop/ortools/ConstraintsManager.py
pyjobshop/ortools/Solver.py
pyjobshop/ortools/VariablesManager.py
pyjobshop/plot.py
pyjobshop/read.py
pyjobshop/utils.py
pyproject.toml
tests/ortools/test_Solver.py
tests/test_Model.py
tests/test_ProblemData.py
tests/test_benchmarks.py
tests/test_utils.py

Rename Machine to Resource

---

pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/cpoptimizer/ConstraintsManager.py
pyjobshop/ortools/ConstraintsManager.py
tests/test_Model.py
tests/test_ProblemData.py

This greatly improves model construction speed for large instances.
This PR:
<details>
**Notes**:
In particular:
- Finally, it is essential that all contributions in this …

Optional setup times as default

---

.github/workflows/CI.yml
docs/source/api/pyjobshop.rst
docs/source/conf.py
pyjobshop/Model.py
pyjobshop/ProblemData.py
pyproject.toml

This PR:
<details>
**Notes**:
In particular:
- Finally, it is essential that all contributions in this PR are license-compatible with PyJobShop's MIT license.
Please check …

Remove enum tools

---

.github/workflows/CI.yml
docs/source/dev/contributing.rst
docs/source/setup/installation.rst
pyproject.toml

This PR:
<details>
**Notes**:
In particular:
- Finally, it is essential that all contributions in this PR are license-compatible with PyJobShop's MIT license.
Please check …

Improve installation & contributing docs

---

pyjobshop/Model.py

This PR: Simplifies and shortens the code. I do not think it needs testing as it is tested implicitly.
<details>
**Notes**:
In particular:
- Finally, it is essential that …

Simplify code by introducing Model._add_constaint()

---

README.md
examples/simple_example.ipynb
pyproject.toml

This PR:
<details>
**Notes**:
In particular:
- Finally, it is essential that all contributions in this PR are license-compatible with PyJobShop's MIT license.
Please check …

Rename RTD urls to pyjobshop.org

---

.github/workflows/CI.yml
docs/README.md
docs/source/dev/contributing.rst
pyjobshop/show_versions.py

This PR:
<details>
**Notes**:
In particular:
- Finally, it is essential that all contributions in this PR are license-compatible with PyJobShop's MIT license.
Please check …

Use `--all-groups` flag

---

pyjobshop/solvers/cpoptimizer/Constraints.py
pyjobshop/solvers/ortools/Constraints.py
pyjobshop/solvers/ortools/Solver.py
pyjobshop/solvers/ortools/Variables.py
pyjobshop/solvers/utils.py
tests/solvers/test_utils.py

This PR refactors the constraint implementation of identical and different resources, as well as consecutive. This is a long due refactor to improve code readability.

Refactor resources and consecutive constraints implementations

---

docs/source/conf.py
pyjobshop/Model.py
pyjobshop/ProblemData.py

This PR:
<details>
**Notes**:
In particular: …

Improve Model documentation

---

pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/solvers/cpoptimizer/Constraints.py
pyjobshop/solvers/ortools/Constraints.py
pyjobshop/solvers/utils.py
tests/solvers/ortools/test_Solver.py
tests/solvers/test_utils.py
tests/test_Model.py
tests/test_ProblemData.py

This PR:
<details>
**Notes**:
In particular: …

Include machine index in Consecutive constraint

---

CITATION.cff
README.md
docs/source/index.rst
docs/source/setup/citing.rst

This PR:
<details>
**Notes**:
In particular: …

Citation data

---

README.md
docs/source/index.rst
pyjobshop/ProblemData.py
pyjobshop/solvers/cpoptimizer/Objective.py
pyjobshop/solvers/cpoptimizer/Variables.py
tests/test_ProblemData.py

This PR:
<details>
**Notes**:
In particular: …

[CP Optimizer] Total setup time objective

---

pyjobshop/ProblemData.py

This PR:
<details>
**Notes**:
In particular: …

Replace NamedTuple with IterableMixin

---

pyjobshop/Model.py
pyjobshop/ProblemData.py
pyjobshop/cli.py
pyjobshop/plot/plot_machine_gantt.py
pyjobshop/plot/plot_resource_usage.py
pyjobshop/plot/plot_task_gantt.py
pyjobshop/read.py
pyjobshop/solve.py
pyjobshop/solvers/cpoptimizer/Solver.py
pyjobshop/solvers/ortools/Solver.py
pyjobshop/solvers/utils.py

This PR:
<details>
**Notes**:
In particular: …

Use Python3.10 syntax

---

pyjobshop/ProblemData.py
pyjobshop/solvers/cpoptimizer/Objective.py
pyjobshop/solvers/ortools/Objective.py
tests/solvers/test_utils.py
tests/test_Model.py
tests/test_ProblemData.py

This PR:
<details>
**Notes**:
In particular: …

Handle edge cases

---

benchmarks/test_benchmarks.py
pyjobshop/solvers/cpoptimizer/Constraints.py

This PR:
<details>
**Notes**:
In particular: …

TSP benchmark

---

pyjobshop/solvers/ortools/Constraints.py

This PR refactors the resource breaks implementation. It came up during #340. This also streamlines the implementation with CP Optimizer.
<details>
**Notes**:
In particular:
- …

[CP-SAT] Refactor resource breaks
